# Generated by Django 4.1.2 on 2022-10-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_regtable_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photos', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Name', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
                ('Brand', models.CharField(max_length=20)),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
